#!/bin/bash

# Manual SafePsy Landing Page Deployment Script
# This script provides step-by-step instructions for deployment

set -e

SERVER_IP="51.159.179.75"
REPO_URL="https://github.com/TTTEN10/SPlandingv1.git"
APP_DIR="/opt/safepsy-landing"

echo "🚀 SafePsy Landing Page Deployment Guide"
echo "========================================"
echo ""
echo "Server IP: $SERVER_IP"
echo "Repository: $REPO_URL"
echo "App Directory: $APP_DIR"
echo ""
echo "📋 Manual Deployment Steps:"
echo ""
echo "1. Connect to your server:"
echo "   ssh root@$SERVER_IP"
echo ""
echo "2. Install Docker and dependencies:"
echo "   apt update"
echo "   apt install -y docker.io docker-compose git curl"
echo "   systemctl start docker"
echo "   systemctl enable docker"
echo ""
echo "3. Create application directory:"
echo "   mkdir -p $APP_DIR"
echo "   cd $APP_DIR"
echo ""
echo "4. Clone the repository:"
echo "   git clone $REPO_URL ."
echo ""
echo "5. Create production environment files:"
echo ""
echo "   Create .env file:"
echo "   cat > .env << 'EOF'"
echo "   NODE_ENV=production"
echo "   PORT=3001"
echo "   DATABASE_URL=file:./prod.db"
echo "   FRONTEND_URL=https://safepsy.com"
echo "   IP_HASHING_ENABLED=false"
echo "   IP_SALT=\$(openssl rand -hex 32)"
echo "   PLAUSIBLE_DOMAIN=safepsy.com"
echo "   ENABLE_CONFIRMATION_EMAIL=false"
echo "   EOF"
echo ""
echo "   Create backend/.env file:"
echo "   cat > backend/.env << 'EOF'"
echo "   NODE_ENV=production"
echo "   PORT=3001"
echo "   DATABASE_URL=file:./prod.db"
echo "   FRONTEND_URL=https://safepsy.com"
echo "   IP_HASHING_ENABLED=false"
echo "   IP_SALT=\$(openssl rand -hex 32)"
echo "   PLAUSIBLE_DOMAIN=safepsy.com"
echo "   ENABLE_CONFIRMATION_EMAIL=false"
echo "   EOF"
echo ""
echo "   Create frontend/.env file:"
echo "   cat > frontend/.env << 'EOF'"
echo "   VITE_PLAUSIBLE_DOMAIN=safepsy.com"
echo "   VITE_API_URL=https://safepsy.com/api"
echo "   EOF"
echo ""
echo "6. Create data and logs directories:"
echo "   mkdir -p data logs"
echo ""
echo "7. Build and start the application:"
echo "   docker-compose up --build -d"
echo ""
echo "8. Check service status:"
echo "   docker-compose ps"
echo "   docker-compose logs -f"
echo ""
echo "9. Test the application:"
echo "   curl http://localhost/health"
echo ""
echo "🌍 Your application will be available at: http://$SERVER_IP"
echo ""
echo "🔧 Useful commands:"
echo "   - View logs: docker-compose logs -f"
echo "   - Restart: docker-compose restart"
echo "   - Stop: docker-compose down"
echo "   - Update: git pull && docker-compose up --build -d"
echo ""
echo "📝 Next steps after deployment:"
echo "   1. Configure your domain (safepsy.com) to point to $SERVER_IP"
echo "   2. Set up SSL certificates for HTTPS"
echo "   3. Configure firewall rules"
echo "   4. Set up monitoring and backups"
echo ""
echo "✅ Deployment guide complete!"
