#!/bin/bash

# SSH Key Setup Script for SafePsy Deployment
# Run this script to add your SSH key to the server

SERVER_IP="51.159.179.75"
SSH_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAeUOnlUT/45PSadp9QNgRCRqgLNnsHYBQzIfqnwMcH9 \"login\""

echo "🔑 Setting up SSH key for SafePsy deployment"
echo "Server: $SERVER_IP"
echo ""

echo "Option 1: Manual SSH key setup (Recommended)"
echo "============================================="
echo ""
echo "1. Connect to your server:"
echo "   ssh root@$SERVER_IP"
echo ""
echo "2. Add your SSH key:"
echo "   mkdir -p ~/.ssh"
echo "   chmod 700 ~/.ssh"
echo "   echo '$SSH_KEY' >> ~/.ssh/authorized_keys"
echo "   chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "3. Test SSH connection:"
echo "   ssh root@$SERVER_IP 'echo \"SSH key setup successful!\"'"
echo ""
echo "Option 2: Use Scaleway Console"
echo "=============================="
echo ""
echo "1. Log into your Scaleway console"
echo "2. Go to your instance"
echo "3. Add the SSH key through the console interface"
echo "4. The key to add is:"
echo "   $SSH_KEY"
echo ""
echo "Option 3: Automated setup (requires password)"
echo "============================================="
echo ""
echo "If you want to use password authentication to set up the key,"
echo "you can run:"
echo ""
echo "   ssh-copy-id -i ~/.ssh/id_ed25519.pub root@$SERVER_IP"
echo ""
echo "Or if you have the key in a file:"
echo "   ssh-copy-id -i /path/to/your/key.pub root@$SERVER_IP"
echo ""
echo "After setting up SSH keys, run the deployment:"
echo "   ./deploy-with-ssh.sh"
echo ""
echo "✅ SSH key setup guide complete!"